/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import java.util.ArrayList;
import java.util.List;

public class App {

    public static void main(String[] args) {

        Graph graph = new Graph();

        graph.addVertex("doaa");
        graph.addVertex("Amara");
        graph.addVertex("Mariam");
        graph.addVertex("Alaa");

        graph.addEdge("doaa","Amara");
        graph.addEdge("doaa", "Mariam");
        graph.addEdge("doaa", "Alaa");
        graph.addEdge("Amara","Mariam");
        graph.addEdge("Mariam","Alaa");
        graph.addEdge("Alaa", "Amara");

        System.out.println(graph.printGraph());

        System.out.println();
        System.out.println(graph.getVertices());

        System.out.println();
        System.out.println(graph.getNeighbors("Amara"));

        System.out.println();
        System.out.println(graph.size());


        //        <<< Code Challenge 36 >>>

        Graph graph1 = new Graph();

        graph1.addVertex("Pandora");
        graph1.addVertex("Arendelle");
        graph1.addVertex("Metroville");
        graph1.addVertex("Monstroplolis");
        graph1.addVertex("Narnia");
        graph1.addVertex("Naboo");

        graph1.addEdge("Pandora", "Arendelle");
        graph1.addEdge("Arendelle", "Metroville");
        graph1.addEdge("Arendelle", "Monstroplolis");
        graph1.addEdge("Metroville", "Narnia");
        graph1.addEdge("Metroville", "Naboo");
        graph1.addEdge("Metroville", "Monstroplolis");
        graph1.addEdge("Monstroplolis", "Naboo");
        graph1.addEdge("Narnia", "Naboo");


        System.out.println(graph1.breadthTraverse( "Pandora"));


        //        <<< Code Challenge 37 >>>

        Graph graph2 = new Graph();

        graph2.addVertex("Pandora");
        graph2.addVertex("Arendelle");
        graph2.addVertex("Metroville");
        graph2.addVertex("Monstroplolis");
        graph2.addVertex("Narnia");
        graph2.addVertex("Naboo");

        graph2.addEdgeWithWeight("Pandora", "Arendelle", 150);
        graph2.addEdgeWithWeight("Arendelle", "Metroville",99);
        graph2.addEdgeWithWeight("Arendelle", "Monstroplolis",42);
        graph2.addEdgeWithWeight("Metroville", "Narnia",37);
        graph2.addEdgeWithWeight("Metroville", "Naboo",26);
        graph2.addEdgeWithWeight("Metroville", "Monstroplolis",105);
        graph2.addEdgeWithWeight("Monstroplolis", "Naboo",73);
        graph2.addEdgeWithWeight("Narnia", "Naboo",250);

        List<String> cities = new ArrayList<>();
        cities.add("Pandora");
        cities.add("Arendelle");
        cities.add("Metroville");

        System.out.println("First Trip ---> "+graph2.businessTrip(graph2,cities));
    }

}

