/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sort;

import sort.insertion.InsertionSort;

import java.util.Arrays;

public class App {

    public static void main(String[] args) {

//        <<< COde Challenge 26 >>>

        int[] arr = {8, 4, 23, 42, 16, 15};

        InsertionSort insertionSort = new InsertionSort();
        insertionSort.insertionSort(arr);

        System.out.println(Arrays.toString(arr));
    }
}
