/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC.linkedList;

import java.Tree.BinaryNode;
import java.Tree.BinaryTree;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());


        LinkedList<String> List1 = new LinkedList<String>();
        LinkedList<Integer> List2 = new LinkedList<>();

        List1.insert("a");
        List1.insert("b");
        List1.insert("a");
//        List1.insert("d");

        List2.insert(6);
        List2.insert(5);
        List2.insert(2);
        List2.insert(4);



//        List1.delete("o");
//        System.out.println(List1);
       //================================================================================
//        List2.sortList(List2);
//        System.out.println(List2);

        //================================================================================
        List2.deleteNode(2, List2);
        System.out.println(List2);

        //==============================================================================
//        System.out.println(List1.listReverser(List1));
        //==============================================================================
//        System.out.println("isPalindrome " + List1.isPalindrome(List1.getHead()));
        //==============================================================================
//        System.out.println(List1.isTextInList(List1,"m"));
//        System.out.println(List1.isTextInList(List1,"f"));
        //==============================================================================
//        System.out.println(List1.isPalindrome(List1));

//        List1.insertAfter(1, "g");

//        System.out.println(List1.zipList(List1,List2));

//        System.out.println(List1.include("o"));

//        System.out.println(List1.Kth(2));


//        List1.append("K");
//        System.out.println(List1);

//        List1.insertAfter("a" , "V");
//        System.out.println(List1);


//       List1.insertBefore("b" , "k");
//       System.out.println(List1);

        //=====================================Tree==================================================
        BinaryTree<String> Bt1= new BinaryTree<>();


    }
}

