/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC.linkedList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


//        Linkedlist<String> newLinkedList= new Linkedlist<>();
//
//        newLinkedList.insert("a");
//        newLinkedList.insert("b");
//        newLinkedList.insert("c");
//        newLinkedList.insert("d");
//
//        System.out.print(newLinkedList.toString());

        LinkedList<String> List1 = new LinkedList<String>();
        LinkedList<Integer> List2 = new LinkedList<Integer>();

        List1.insert("a");
        List1.insert("b");
        List1.insert("c");
        List1.insert("d");

        List2.insert(1);
        List2.insert(2);
        List2.insert(3);
        List2.insert(4);


        System.out.println(List1.listReverser(List1));
//        List1.insertAfter(1, "g");

//        System.out.println(List1.zipList(List1,List2));

//        System.out.println(List1.includes("c"));

//        System.out.println(List1.Kth(2));


//        List1.append("K");
//        System.out.println(List1);

//        List1.insertAfter("a" , "V");
//        System.out.println(List1);

    }
}

