/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        BinaryTree<Integer> binaryTree = new BinaryTree<Integer>();

        binaryTree.insert(50);
        binaryTree.insert(10);
        binaryTree.insert(60);
        binaryTree.insert(5);
        binaryTree.insert(20);
        binaryTree.insert(55);
        binaryTree.insert(70);

        System.out.println(binaryTree);

        BinaryTree<String> Doaa= new BinaryTree<>();
        Doaa.insert("D");
        Doaa.insert("O");
        Doaa.insert("A");
        Doaa.insert("A");
        Doaa.insert("C");

        System.out.println("Inorder traversal of numbers" + " ");
        binaryTree.inorderTraversal();

        System.out.println(" ");

        System.out.println("pre traversal of numbers" + " ");
        binaryTree.preorderTraversal();

        System.out.println(" ");

        System.out.println("post traversal of numbers" + " ");
        binaryTree.postorderTraversal();

    }
}
