/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        BinarySearchTree<Integer> binarySearchTree= new BinarySearchTree<Integer>();

        binarySearchTree.insert(50);
        binarySearchTree.insert(10);
        binarySearchTree.insert(60);
        binarySearchTree.insert(5);
//        binarySearchTree.insert(20);
//        binarySearchTree.insert(55);
//        binarySearchTree.insert(70);

        System.out.println(binarySearchTree);

        BinarySearchTree<String> Doaa= new BinarySearchTree<>();
        Doaa.insert("D");
        Doaa.insert("O");
        Doaa.insert("A");
        Doaa.insert("A");
        Doaa.insert("C");

        System.out.println("Inorder traversal of numbers" + " ");
        binarySearchTree.inorderTraversal();

        System.out.println(" ");

        System.out.println("pre traversal of numbers" + " ");
        binarySearchTree.preorderTraversal();

        System.out.println(" ");

        System.out.println("post traversal of numbers" + " ");
        binarySearchTree.postorderTraversal();

    }
}
