/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

import java.io.IOException;
import java.util.Stack;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {

        System.out.println(new App().getGreeting());

        Stack stack = new Stack();

        stack.push("D");
        stack.push("O");
        stack.push("A");
        stack.push("A");

//        System.out.println(stack.toString());
//
//        System.out.println(stack.pop());
//        System.out.println(stack.pop());
//
//        System.out.println(stack.peek());

        //===========================Queue=====================
        Queue queue= new Queue();
        queue.enqueue("D");
        queue.enqueue("O");
        queue.enqueue("A");
        queue.enqueue("A");

        System.out.println(queue);

        System.out.println(queue.dequeue());

        System.out.println(queue.peek());

        //==============================PsudoQueue=========================
        PseudoQueue queue1 = new PseudoQueue();

        queue1.enqueue("20");
        queue1.enqueue("1");
        queue1.enqueue("2");
        queue1.enqueue("3");
        queue1.enqueue("4");


        System.out.println(queue1.dequeue());

    }

}
