/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        Stack stack = new Stack();

        stack.push("D");
        stack.push("O");
        stack.push("A");
        stack.push("A");

        System.out.println(stack);


        System.out.println(stack.pop());

    }



}
