/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HashTabels;

import HashTabels.binaryTree.BinaryTree;
import HashTabels.binaryTree.Node;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    public void test(){

        HashTable<String, Integer> clubs = new HashTable<String, Integer>();

        assertTrue(clubs.isEmpty());

        clubs.add("Real Madrid",100);
        assertEquals(1,clubs.getSize());

        clubs.add("Barcelona", 200);
        assertEquals(2,clubs.getSize());
        assertFalse(clubs.isEmpty());

        clubs.remove("Barcelona");
        assertEquals(1,clubs.getSize());

        assertTrue(clubs.contains("Real Madrid"));
        assertFalse(clubs.contains("Man United"));

        clubs.remove("Real Madrid");
        assertTrue(clubs.isEmpty());

    }

    //    <<< Code Challenge 32 >>>

    @Test
    public void intersectionTreeTest(){

        HashTable<Integer,Integer> trees = new HashTable<Integer, Integer>();
        BinaryTree tree1 = new BinaryTree();
        BinaryTree tree2 = new BinaryTree();

        tree1.setRoot(new Node(150));
        tree1.getRoot().setLeft(new Node(100));
        tree1.getRoot().setRight(new Node(250));
        tree1.getRoot().getRight().setLeft(new Node(200));
        tree1.getRoot().getRight().setRight(new Node(350));

        tree2.setRoot(new Node(42));
        tree2.getRoot().setLeft(new Node(100));
        tree2.getRoot().setRight(new Node(600));
        tree2.getRoot().getRight().setLeft(new Node(200));
        tree2.getRoot().getRight().setRight(new Node(350));

        assertEquals("[100, 200, 350]", trees.treeIntersection(tree1,tree2).toString());

    }

    @Test
    public void intersectionTreeTestNoResults(){

        HashTable<Integer,Integer> trees = new HashTable<Integer, Integer>();
        BinaryTree tree1 = new BinaryTree();
        BinaryTree tree2 = new BinaryTree();

        tree1.setRoot(new Node(150));
        tree1.getRoot().setLeft(new Node(100));
        tree1.getRoot().setRight(new Node(250));
        tree1.getRoot().getRight().setLeft(new Node(200));
        tree1.getRoot().getRight().setRight(new Node(350));

        tree2.setRoot(new Node(42));
        tree2.getRoot().setLeft(new Node(101));
        tree2.getRoot().setRight(new Node(600));
        tree2.getRoot().getRight().setLeft(new Node(201));
        tree2.getRoot().getRight().setRight(new Node(310));

        assertEquals("[]", trees.treeIntersection(tree1,tree2).toString());

    }

    @Test
    public void intersectionTreeDifferentNumOfNodes(){

        HashTable<Integer,Integer> trees = new HashTable<Integer, Integer>();
        BinaryTree tree1 = new BinaryTree();
        BinaryTree tree2 = new BinaryTree();

        tree1.setRoot(new Node(150));
        tree1.getRoot().setLeft(new Node(100));
        tree1.getRoot().setRight(new Node(250));
        tree1.getRoot().getRight().setLeft(new Node(200));
        tree1.getRoot().getRight().setRight(new Node(350));

        tree2.setRoot(new Node(42));
        tree2.getRoot().setLeft(new Node(100));
        tree2.getRoot().setRight(new Node(600));
        tree2.getRoot().getRight().setLeft(new Node(200));

        assertEquals("[100, 200]", trees.treeIntersection(tree1,tree2).toString());

    }
}
