/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    public void addVertex(){

        Graph graph = new Graph();

        graph.addVertex("doaa");
        graph.addVertex("Amara");

        assertNotNull(graph.getVertices());
        assertEquals(2,graph.size());
    }

//    @Test
//    public void addEdge(){
//
//        Graph graph = new Graph();
//
//        graph.addVertex("doaa");
//        graph.addVertex("Mariam");
//        graph.addEdge("doaa", "Mariam");
//
//        assertEquals("Vertex{label='Mariam'}[Vertex{label='doaa'}]Vertex{label='doaa'}[Vertex{label='Mariam'}]", graph.printGraph());
//    }

    @Test
    public void vertexNeighbors(){

        Graph graph = new Graph();

        graph.addVertex("doaa");
        graph.addVertex("Mariam");
        graph.addVertex("Alaa");
        graph.addVertex("Amara");
        graph.addEdge("doaa", "Alaa");
        graph.addEdge("doaa", "Mariam");
        graph.addEdge("Amara", "Mariam");

        assertEquals("[Vertex{label='Alaa'}, Vertex{label='Mariam'}]",graph.getNeighbors("doaa").toString());
        assertEquals("[Vertex{label='Mariam'}]", graph.getNeighbors("Amara").toString());

    }

    @Test
    public void emptyGraph(){

        Graph graph = new Graph();
        assertEquals(0,graph.size());
        assertEquals("[]", graph.getVertices().toString());
    }



    @Test
    public void oneVertexAndOneEdge(){
        Graph graph = new Graph();

        graph.addVertex("doaa");

        assertEquals("Vertex{label='doaa'}[]",graph.printGraph());
    }

    //    <<<Code Challenge 36 >>
    @Test
    public void breadthFirst(){

        Graph graph1 = new Graph();

        graph1.addVertex("Pandora");
        graph1.addVertex("Arendelle");
        graph1.addVertex("Metroville");
        graph1.addVertex("Monstroplolis");
        graph1.addVertex("Narnia");
        graph1.addVertex("Naboo");

        graph1.addEdge("Pandora", "Arendelle");
        graph1.addEdge("Arendelle", "Metroville");
        graph1.addEdge("Arendelle", "Monstroplolis");
        graph1.addEdge("Metroville", "Narnia");
        graph1.addEdge("Metroville", "Naboo");
        graph1.addEdge("Metroville", "Monstroplolis");
        graph1.addEdge("Monstroplolis", "Naboo");
        graph1.addEdge("Narnia", "Naboo");

        assertEquals("[Pandora, Arendelle, Metroville, Monstroplolis, Narnia, Naboo]", graph1.breadthTraverse("Pandora").toString());
    }

}
